#!/bin/bash
shopt -s nullglob
set -eu

# Genesis Kit `blueprint' Hook
#
# This script outputs the list of merge files needed to support the desired
# feature set selected by the environment parameter file.  As generated, it
# lists all *.yml files in the base, then all *.yml files in each detected
# feature directory, in the order the features are specified in the environment
# yml file.  If finer control is desired, add logic around the wants_kit_feature()
# function (takes a feature as a string, returns exit code 0 if present, non-
# zero exit code otherwise).

validate_features single-az pre-start-script \
  hooks-environment

declare -a manifests
manifests+=(manifests/buildkite-agent.yml)
manifests+=(manifests/operators/aws-credentials.yml)
manifests+=(manifests/operators/git-ssh-private-key.yml)
manifests+=(manifests/operators/scale.yml)

if want_feature single-az; then
  manifests+=(ops/single-az.yml)
fi
if want_feature hooks-environment; then
  manifests+=(ops/hooks-environment.yml)
fi
if want_feature pre-start-script; then
  manifests+=(manifests/operators/pre-start-script.yml)
fi

echo "${manifests[@]}"
